### PR TITLE
Ensure title state isn't remembered between parses

### PR DESCRIPTION
**Pull request by rjkip**
Previously, subsequent parses would be influenced by title state (title characters, current level, etc.) from the previous parse.

### CODE REVIEW

**Comment by Gregwar** [comment]
Looks like this now conflicts

**Comment by rjkip** [comment]
I can look into resolving these tomorrow.

**Comment by rjkip** [comment]
@Gregwar, all done. Tests fail on 5.3.3 due to some kind of openssl extension error, but that's a whole other issue :wink:

**Comment by Gregwar** [comment]
Thanks for contributing

**Pull request merged**
