### PR TITLE
[SECURITY] Prevent Local File Inclusion Attacks

### PR DESCRIPTION
**Pull request by paragonie-scott**
Allows the `include` directive to be disabled outright. Alternatively, file inclusion can be jailed to a specific directory an all `include` directives to outside the directory will fail.

Includes unit tests.

### CODE REVIEW

**Comment by Gregwar** [comment]
Sounds good to me
Thanks for contributing

**Comment by paragonie-scott** [comment]
Happy to help. Any chance we could get a release tagged this morning?

**Comment by Gregwar** [comment]
Tagged `v1.0.3`

**Comment by sstok** [comment]
May I suggest for a next major version (whenever it's released) to disable the include directive by default, and require explicitly enabling this? So there is less change of missing this 👍

**Pull request merged**
